name: diffusion
action_horizon: ${action_horizon}
pred_horizon: ${pred_horizon}
obs_horizon: ${obs_horizon}
first_action_index: 0
beta_schedule: squaredcos_cap_v2
inference_steps: 16
prediction_type: epsilon
num_diffusion_iters: 100
clip_sample: true

loss_fn: MSELoss  # MSELoss | L1Loss
confusion_loss_beta: 0.0

projection_dim: 128

defaults:
  - diffusion_model: unet