training:
  gpu_id: 0
  
  actor_lr: 1e-4
  encoder_lr: ${training.actor_lr}
  clip_grad_norm: false
  clip_sample: true
  mixed_precision: false
  
  num_epochs: 200
  batch_size: 64
  start_epoch: 0
  steps_per_epoch: 400 # Set to -1 to do one pass over the dataset

  sample_every: 5
  
  load_checkpoint_run_id: null
  checkpoint_model: true
  model_save_dir: models
  checkpoint_interval: -1

  ema:
    use: false
    decay: 0.999
    switch: false
