seed: null
torch_deterministic: true
headless: true
reset_on_failure: false
reset_every_iteration: true
reset_on_success: false
eval_interval: 5
checkpoint_interval: 10


total_timesteps: 500_000_000
num_envs: 512
num_minibatches: 1
update_epochs: 10
num_env_steps: 850
data_collection_steps: ${num_env_steps}

residual_policy:
  _target_: src.models.residual.ResidualPolicy
  init_logstd: -2
  action_head_std: 0.0
  action_scale: 0.1
  actor_hidden_size: 512
  actor_num_layers: 2
  critic_hidden_size: 512
  critic_num_layers: 2
  actor_activation: ReLU
  critic_activation: ${residual_policy.actor_activation}
  critic_last_layer_bias_const: 0.5

# Algorithm specific arguments
learning_rate: 1e-4
lr_scheduler:
  name: cosine
  warmup_steps: 5
  
gamma: 0.999
gae_lambda: 0.95
norm_adv: true
normalize_reward: true
clip_coef: 0.2
clip_vloss: true
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
target_kl: 0.1
residual_regularization: 0.01
n_iterations_train_only_value: 0
truncation_as_done: true
norm_grads: false

# Calculate the batch size as the data collection steps times the number of environments
batch_size: ${eval:'${data_collection_steps} * ${num_envs}'}
minibatch_size: ${eval:'${batch_size} // ${num_minibatches}'}
num_iterations: ${eval:'${total_timesteps} // ${batch_size}'}

action_type: pos
act_rot_repr: rot_6d

wandb:
  entity: ankile
  project: residual-ppo-2

debug: false